const menuToggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav');
menuToggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));});
const featuredProducts={e6013:'product-e6013.html',e7018:'product-e7018.html',e7016:'product-e7016.html'};
const params=new URLSearchParams(location.search);const requestedProduct=params.get('product');if(location.pathname.endsWith('/product.html')&&featuredProducts[requestedProduct]){location.replace(featuredProducts[requestedProduct]);}
const productMenu=[['Welding Electrodes',[['E6013','e6013'],['E7018','e7018'],['E7016','e7016'],['E308L','e308l-electrode'],['E309L','e309l-electrode'],['E316L','e316l-electrode'],['Hardfacing','hardfacing'],['Cast Iron','cast-iron']]],['MIG / TIG / FCAW / SAW Wires',[['ER70S-6','er70s6'],['ER70S-2','er70s2'],['ER308L','er308l'],['ER309L','er309l'],['ER316L','er316l'],['ER4043','er4043'],['ER5356','er5356'],['E71T Series','e71t1'],['EM12K','em12k']]],['Cutting & Grinding Wheels',[['Cut-Off Wheels','cutoff'],['Grinding Wheels','grinding'],['Ultra-Thin Wheels','ultrathin'],['Flap Discs','flap-disc'],['Fibre Discs','fibre-disc']]],['Industrial Fasteners',[['Hex Bolts','hex-bolt'],['Stud Bolts','stud-bolt'],['U-Bolts','u-bolt'],['Hex Nuts','hex-nut'],['Washers','washer'],['Threaded Rods','threaded-rod']]],['HVAC Products',[['Pipe Clamps','pipe-clamp'],['Rubber-Lined Clamps','rubber-lined-clamp'],['Split Clamps','split-clamp'],['Pipe Hangers','pipe-hanger'],['Strut Channels','strut-channel'],['Beam Clamps','beam-clamp']]],['Anti-Vibration Products',[['Rubber Mounts','rubber-mount'],['Spring Isolators','spring-isolator'],['Spring Hangers','spring-hanger'],['Neoprene Pads','neoprene-pad'],['Machine Mounts','machine-mount'],['Shock Mounts','shock-mount']]]];
function buildProductMenu(){document.querySelectorAll('.products-nav-link,.nav a[href="products.html"]').forEach(link=>{if(link.closest('.nav-dropdown'))return;const wrap=document.createElement('div');wrap.className='nav-dropdown';const button=document.createElement('button');button.className='nav-products-button';button.type='button';button.innerHTML='Products <span>⌄</span>';const panel=document.createElement('div');panel.className='nav-product-panel';productMenu.forEach(([cat,items])=>{const branch=document.createElement('div');branch.className='nav-product-branch';const catBtn=document.createElement('button');catBtn.type='button';catBtn.className='nav-category-button';catBtn.innerHTML=`<span>${cat}</span><b>›</b>`;const list=document.createElement('div');list.className='nav-product-list';items.forEach(([name,slug])=>{const a=document.createElement('a');a.href=featuredProducts[slug]||`product.html?product=${slug}`;a.textContent=name;list.appendChild(a);});catBtn.addEventListener('click',e=>{e.stopPropagation();document.querySelectorAll('.nav-product-branch.open').forEach(x=>{if(x!==branch)x.classList.remove('open');});branch.classList.toggle('open');});branch.append(catBtn,list);panel.appendChild(branch);});button.addEventListener('click',e=>{e.stopPropagation();wrap.classList.toggle('open');});wrap.append(button,panel);link.replaceWith(wrap);});}
buildProductMenu();
document.addEventListener('click',e=>{if(!e.target.closest('.nav-dropdown'))document.querySelectorAll('.nav-dropdown.open').forEach(x=>x.classList.remove('open'));});
document.querySelectorAll('.nav a').forEach(link=>link.addEventListener('click',()=>nav?.classList.remove('open')));
if(document.querySelector('.product-image-placeholder')){const link=document.createElement('link');link.rel='stylesheet';link.href='product-visuals.css';document.head.appendChild(link);}
const productCta=document.querySelector('.hero-actions .btn.primary');if(productCta&&(location.pathname.endsWith('/index.html')||location.pathname.endsWith('/')))productCta.href='products.html';
const productSections=['welding','wires','abrasives','fasteners','hvac','vibration'];document.querySelectorAll('.product-family .text-link').forEach((link,index)=>{if(productSections[index])link.href=`products.html#${productSections[index]}`;});
const detailLinks={'Mild Steel':'e6013','Low Hydrogen':'e7018','Stainless Steel':'e308l-electrode','Carbon steel MIG':'er70s6','Stainless MIG / TIG':'er308l','Aluminium':'er4043','Cutting Wheels':'cutoff','Grinding Wheels':'grinding','Bolts & Studs':'hex-bolt','Pipe Supports':'pipe-clamp','Channel Systems':'strut-channel','Rubber Isolation':'rubber-mount','Spring Isolation':'spring-isolator'};
document.querySelectorAll('.detail-card').forEach(card=>{const heading=card.querySelector('h3');if(!heading||card.querySelector('.detail-link'))return;const slug=detailLinks[heading.textContent.trim()];if(slug){const a=document.createElement('a');a.className='text-link detail-link';a.href=featuredProducts[slug]||`product.html?product=${slug}`;a.textContent='View product details →';card.appendChild(a);}});
document.querySelectorAll('.category-toggle').forEach(btn=>{btn.addEventListener('click',()=>{const open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));btn.nextElementSibling?.classList.toggle('open',!open);});});
document.querySelectorAll('.enquiry-form').forEach(form=>{if((form.getAttribute('action')||'').startsWith('mailto:'))return;form.addEventListener('submit',event=>{event.preventDefault();alert('Thank you. Your enquiry form is ready; connect it to a dedicated form service before launch.');});});

// Temporary online reference photography. These are generic/reference images only and are not CLAMPCO product photography.
const onlineProductImages={
 welding:['https://mapleweld.ca/cdn/shop/files/6013_1024x1024.png?v=1739194463','https://www.weldmaterial.com/Uploads/696c410a4b45b.jpg','https://weldingcity-usa.com/cdn/shop/products/E308L-16_no_logo.jpg?v=1669821878'],
 wire:['https://static.grainger.com/rp/s/is/image/Grainger/30XN90_GC01?%24adapimg%24=&hei=536&wid=536','https://www.airgas.com/medias/HAR-0308LH8-B.jpg-1200Wx1200H?context=bWFzdGVyfHJvb3R8MzAzMDI4fGltYWdlL2pwZWd8aDA2L2g3NC8xMTg4MDA4MzM5MDQ5NC5qcGd8OTNmMmUxNTc3NmQ4MmRjYzBiMmJlZTkxY2NlYTIzMjU3ZjQ1ZjZmNTA0M2ZkOWJjMDRiZmQ4Njg1MTgzNTlmYQ','https://down-br.img.susercontent.com/file/br-11134207-7r98o-mdnc071zqlrt1b'],
 wheel:['https://www.cuttingdiscfactory.com/cuttingdiscfactory/2024/08/23/196a9632.jpg','https://multimedia.3m.com/mws/media/2306025J/3m-green-corps-cut-off-wheel-out-of-package.jpg','https://multimedia.3m.com/mws/media/424849J/3m-green-corps-cut-off-wheels.jpg']
};
function loadGalleryCss(){if(!document.querySelector('link[href="online-product-gallery.css"]')){const css=document.createElement('link');css.rel='stylesheet';css.href='online-product-gallery.css';document.head.appendChild(css);}}
function buildReferenceGallery(slug,kind,target){if(!target||target.querySelector('.online-product-gallery'))return;const urls=onlineProductImages[kind];if(!urls)return;loadGalleryCss();const gallery=document.createElement('div');gallery.className='online-product-gallery';gallery.innerHTML=`<div class="online-gallery-head"><div><span class="eyebrow">PRODUCT REFERENCE IMAGES</span><h3>Visual reference for ${slug.toUpperCase()}</h3></div><span class="reference-badge">TEMPORARY ONLINE REFERENCE</span></div><div class="online-gallery-grid">${urls.map((url,i)=>`<figure><div class="online-image-wrap"><img src="${url}" alt="${slug.toUpperCase()} product reference image ${i+1}" loading="lazy" referrerpolicy="no-referrer"><span>Reference image</span></div><figcaption>Reference view ${i+1} · Final CLAMPCO photography will replace this image.</figcaption></figure>`).join('')}</div><p class="online-gallery-note">These images are used temporarily for website layout and product-reference presentation. They are not representations of final CLAMPCO packaging, branding or exact supplied configuration.</p>`;target.appendChild(gallery);}
function injectOnlineProductGallery(){const root=document.getElementById('product-detail');if(!root||root.dataset.galleryReady==='true')return;const placeholder=root.querySelector('.product-image-placeholder');if(!placeholder)return;const slug=new URLSearchParams(location.search).get('product')||'';const kind=placeholder.className.match(/(welding|wire|wheel)-detail-art/)?.[1];if(!kind||!onlineProductImages[kind])return;root.dataset.galleryReady='true';buildReferenceGallery(slug,kind,placeholder.parentElement);placeholder.replaceWith(placeholder);}
if(document.getElementById('product-detail')){const observer=new MutationObserver(injectOnlineProductGallery);observer.observe(document.getElementById('product-detail'),{childList:true,subtree:true});setTimeout(injectOnlineProductGallery,100);}

const featuredReferencePages={
 'product-e6013.html':['e6013','welding'],
 'product-e7018.html':['e7018','welding'],
 'product-e7016.html':['e7016','welding']
};
const featuredKey=Object.keys(featuredReferencePages).find(name=>location.pathname.endsWith('/'+name)||location.pathname.endsWith(name));
if(featuredKey){const [slug,kind]=featuredReferencePages[featuredKey];const host=document.querySelector('.featured-grid .product-render');const section=host?.closest('.featured-hero')?.parentElement;if(section)buildReferenceGallery(slug,kind,section.querySelector('.featured-section .container')||section);}
